#!/usr/bin/env php
<?php
require_once __DIR__ . '/../vendor/autoload.php';
 
use Symfony\Component\Console\Application;
use Console\App\Commands\NotifyCommand;
use Console\App\Commands\ClearcacheCommand;
 
$app = new Application();
$app->add(new NotifyCommand());
$app->add(new ClearcacheCommand());
$app->run();